version: '3.9'

services:
  app:
    container_name: emis-health-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.local
    environment:
      - NODE_ENV=local
    # volumes:
    #   - .:/usr/app
