name: Build and Push to ECR

on:
  push:
    branches:
      - task/devops-v1  # Adjust to your main branch
  pull_request:
    branches:
      - task/devops-v1  # Adjust to your main branch
env:
  ECR_REPOSITORY_URI: ${{ secrets.ECR_REPOSITORY_URI }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::635395011038:role/emis-ecr-access-role
          role-session-name: emis-github-actions-session
          aws-region: ${{ env.AWS_REGION }}

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify the Node.js version

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install -g @go-task/cli

      # Formatting checks using Prettier
      - name: Run Prettier check
        run: npm run prettier -- --check "**/*.js"
        # Ensure you have a script like "prettier": "prettier" in your package.json

      # Security checks using npm audit
      - name: Run npm audit for security vulnerabilities
        run: npm audit --audit-level=high

      # Run tests (optional, add your testing script here)
      - name: Run tests
        run: npm test

      # Not checking for code coverage in this example due to key is not  available
      # SonarQube scan
      # - name: Run SonarQube scan
      #   uses: sonarsource/sonarcloud-github-action@v1.11
      #   with:
      #     projectKey: emis-project-api  # Replace with your SonarQube project key
      #     organization: emis-org  # Replace with your SonarQube organization
      #     token: $SONAR_TOKEN

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: ecr_login
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

      # - name: Install Task
      #   run: |
      #     sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

      # Verify Task is installed
      - name: Verify Task installation
        run: task --version

      # Build Docker image
      - name: Build Docker image
        run: task build

      # Push Docker image to ECR
      - name: Push Docker image to ECR
        run: task ecr-push
