name: Terraform CI/CD

on:
  workflow_dispatch:
  
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ASSUME_ROLE_ARN: ${{ secrets.ASSUME_ROLE_ARN }}
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    name: 'Terraform Lint, Security Check, and Deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/stacks/eks

    env:
      TF_VERSION: '1.8.5'
      TFLINT_VERSION: '0.46.1'  # Updated to a more recent version
      TFSEC_VERSION: '1.28.1'   # Updated to a more recent version
      WORKING_DIR: 'infrastructure/stacks/eks'

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{env.ASSUME_ROLE_ARN}}
        role-session-name: emis-github-actions-infra-session
        aws-region: ${{ env.AWS_REGION }}


    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: 'Install TFLint'
      run: |
        curl -sLo tflint.zip https://github.com/terraform-linters/tflint/releases/download/v${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip
        unzip tflint.zip -d /usr/local/bin/
        tflint --version

    - name: 'Install tfsec'
      run: |
        curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v${{ env.TFSEC_VERSION }}/tfsec-linux-amd64
        chmod +x tfsec
        mv tfsec /usr/local/bin/
        tfsec --version

    - name: 'Terraform Init'
      run: terraform init
      working-directory: ${{ env.WORKING_DIR }}

     
    - name: 'Terraform Format'
      run: terraform fmt
      working-directory: ${{ env.WORKING_DIR }}


    - name: 'Terraform Validate'
      run: terraform validate
      working-directory: ${{ env.WORKING_DIR }}


    - name: 'TFLint'
      run: |
        tflint --init
        tflint
      working-directory: ${{ env.WORKING_DIR }}

    # - name: 'tfsec'
    #   run: tfsec .

    - name: 'Terraform Plan'
      run: terraform plan -out=tfplan
      working-directory: ${{ env.WORKING_DIR }}

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve tfplan
      working-directory: ${{ env.WORKING_DIR }}